### ISSUE TITLE
Support custom "createdAt" and "updatedAt" field names

### ISSUE THREAD

**Issue by tzellman** [balderdashy/waterline-schema#27] opened 2015-05-15 21:38 UTC
It would be nice to be able to override the field names used for auto generated fields, such as createdAt and updatedAt. For example, I may want to call them "created_timestamp" and "updated_timestamp", respectively.

Not a huge deal, just thought it would be a nice feature to support. I don't mind submitting a pull request with a potential solution.

Thanks!

**Comment by dmarcelino** [comment] 2015-05-16 00:29
Hi @tzellman, thanks for contributing. Your issue is partially a duplicate of balderdashy/waterline#754 and the functionality you requested is already submitted in PRs balderdashy/waterline#946 and #23. Once these 2 PRs get merged it will be possible to do the following in the model definition:
```js
          autoCreatedAt: "created_timestamp",
          autoUpdatedAt: "updated_timestamp",
```

Please continue this thread on those open issues/PRs to avoid repetition. Meanwhile I'm closing this as a duplicate. Please re-open if you disagree. Thanks!

**Closed by dmarcelino** 2015-05-16 00:29 UTC

**Comment by tzellman** [comment] 2015-05-16 00:35
Sure thing! I didn't think to check in the main waterline repo. I'll follow
the referenced issues. Thanks!
